nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: ghcr.io/ORG/APP
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env: []
envFromSecret: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  # Advanced scaling policies
  scaleDown:
    stabilizationWindowSeconds: 300
    policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
    selectPolicy: Min
  scaleUp:
    stabilizationWindowSeconds: 60
    policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
    selectPolicy: Max
  # Custom metrics for advanced scaling
  customMetrics: []
    # Example custom metrics:
    # - type: Pods
    #   metricName: http_requests_per_second
    #   targetType: AverageValue
    #   targetAverageValue: 100
    # - type: Object
    #   metricName: requests_per_second
    #   describedObject:
    #     apiVersion: apps/v1
    #     kind: Deployment
    #     name: erp-api
    #   targetType: Value
    #   targetValue: 1000

# Vertical Pod Autoscaler configuration
verticalPodAutoscaling:
  enabled: true
  updateMode: "Recreate"
  minCPU: 100m
  maxCPU: 2000m
  minMemory: 128Mi
  maxMemory: 4096Mi
  # Safety mechanisms
  controlledResources: ["cpu", "memory"]
  # Recommendation-only mode for safer rollout
  recommendationMode: true

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - example.com
      secretName: app-tls

# Prometheus monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    scrape: true
    port: 9090
    path: "/metrics"
    interval: "30s"
    labels:
      app: "{{ include \"app.name\" . }}"
      release: "{{ .Release.Name }}"

# Service monitor for Prometheus Operator
serviceMonitor:
  enabled: true
  namespace: "monitoring"
  interval: "30s"
  scrapeTimeout: "10s"
  labels:
    release: "prometheus"
  selector:
    matchLabels:
      app: "{{ include \"app.name\" . }}"


