apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 79.10.0
    helm:
      values: |
        # Full name override to prevent conflicts
        fullnameOverride: prometheus
        
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                cpu: 1000m
                memory: 2Gi

        grafana:
          enabled: true
          adminPassword: "changeme"
          persistence:
            enabled: true
            size: 10Gi
            accessModes:
              - ReadWriteOnce
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
          initChownData:
            enabled: false
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            hosts:
              - grafana.codevertexitsolutions.com
            path: /
            pathType: Prefix
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.codevertexitsolutions.com

        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi

        nodeExporter:
          enabled: true

        kubeStateMetrics:
          enabled: true

        # Disable admission webhooks to prevent RBAC conflicts
        # These webhooks cause "already exists" errors during sync
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


