apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: shared-infra
  labels:
    app: ollama
    tier: shared
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http
