apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://apache.github.io/superset
    targetRevision: 0.12.1
    chart: superset
    helm:
      values: |
        init:
          adminUser:
            username: admin
            firstname: Admin
            lastname: User
            email: admin@bengobox.com
            password: admin
        postgresql:
          enabled: false
        redis:
          enabled: false
        supersetNode:
          connections:
            db_host: postgresql.default.svc.cluster.local
            db_port: 5432
            db_user: postgres
            db_pass: postgres
            db_name: superset
            redis_host: redis-master.default.svc.cluster.local
            redis_port: 6379
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
