name: Install DevOps Tools

description: 'Reusable composite action to install all required DevOps tools'

inputs:
  install_trivy:
    description: 'Install Trivy security scanner'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        VER=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        curl -LO https://dl.k8s.io/release/${VER}/bin/linux/amd64/kubectl
        sudo install -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client=true

    - name: Install Helm
      shell: bash
      run: |
        # Try official script first, fallback to direct download if it fails
        if ! curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash; then
          echo "Official script failed, trying direct download..."
          HELM_VERSION="v3.16.1"
          curl -fsSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o /tmp/helm.tar.gz
          tar -zxvf /tmp/helm.tar.gz -C /tmp
          sudo mv /tmp/linux-amd64/helm /usr/local/bin/helm
          sudo chmod +x /usr/local/bin/helm
          rm -rf /tmp/helm.tar.gz /tmp/linux-amd64
        fi
        helm version

    - name: Install yq
      shell: bash
      run: |
        sudo curl -L "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" -o /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq
        yq --version

    - name: Install Trivy (optional)
      shell: bash
      if: ${{ inputs.install_trivy == 'true' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install trivy -y
        trivy --version

    - name: Install ArgoCD CLI
      shell: bash
      run: |
        ARGOCD_VERSION="v2.13.0"
        curl -sSL -o /tmp/argocd https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-amd64
        sudo install -m 0755 /tmp/argocd /usr/local/bin/argocd
        argocd version --client || true
        rm -f /tmp/argocd

    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq curl git openssl
