apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-data
  namespace: logistics
  labels:
    app: tileserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
