apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valhalla-data
  namespace: logistics
  labels:
    app: valhalla
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
