apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 14.6.13
    helm:
      values: |
        ## Bitnami RabbitMQ Helm Chart Values
        ## Shared Broker for Asynchronous Workloads

        auth:
          username: user
          # password: ""  # Prefer setting via external secret; if empty, chart will generate

        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        persistence:
          enabled: true
          size: 10Gi
          storageClass: ""

        priorityClassName: db-critical

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: infra

        networkPolicy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


