apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'email'
      routes:
      - match:
          severity: critical
        receiver: email
        continue: true
    receivers:
    - name: 'email'
      email_configs:
      - to: 'codevertexitsolutions@gmail.com'
        from: 'alerts@codevertexitsolutions.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'codevertexitsolutions@gmail.com'
        auth_password: '<APP_PASSWORD>'
        headers:
          Subject: '{{ template "email.default.subject" . }}'

