apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erp-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bengo-Hub/devops-k8s.git
    targetRevision: main
    path: charts/app
    helm:
      values: |
        image:
          repository: docker.io/codevertex/erp-ui
          tag: latest

        service:
          port: 80
          targetPort: 3000

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 8
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80

        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: erp.masterspace.co.ke
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - erp.masterspace.co.ke
              secretName: erp-masterspace-tls

        envFromSecret: erp-ui-env

        # Vertical Pod Autoscaler for optimal resource allocation
        verticalPodAutoscaling:
          enabled: true
          updateMode: "Recreate"
          minCPU: 50m
          maxCPU: 1000m
          minMemory: 128Mi
          maxMemory: 2Gi
          controlledResources: ["cpu", "memory"]
          controlledValues: RequestsAndLimits
          recommendationMode: false
  destination:
    server: https://kubernetes.default.svc
    namespace: erp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
