apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketflow-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bengo-Hub/devops-k8s.git
    targetRevision: main
    path: charts/app
    helm:
      valueFiles:
        - ../../apps/marketflow-ui/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: marketflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
