{{- if .Values.persistence.enabled }}
{{- $pvcName := printf "%s-media" (include "app.fullname" .) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    app: {{ include "app.fullname" . }}
    chart: {{ include "app.chart" . }}
  annotations:
    # ArgoCD: Ignore immutable fields that Kubernetes sets automatically when binding
    # volumeName is set by Kubernetes when PVC binds to PV - never include it in spec
    argocd.argoproj.io/ignore-differences: |
      - jsonPointers:
        - /spec/volumeName
        - /spec/volumeMode
        - /status
        - /metadata/finalizers
        - /metadata/managedFields
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  # Never set volumeName - Kubernetes sets it when binding to PV
{{- end }}
