{{- if .Values.persistence.enabled }}
{{- $pvcName := printf "%s-media" (include "app.fullname" .) }}
{{- $existing := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName }}
{{- if not $existing }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    app: {{ include "app.fullname" . }}
    chart: {{ include "app.chart" . }}
  annotations:
    # ArgoCD: Ignore immutable fields that Kubernetes sets automatically when binding
    # volumeName is set by Kubernetes when PVC binds to PV - never include it in spec
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }}
