{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" . }}-media
  labels:
    app: {{ include "app.fullname" . }}
    chart: {{ include "app.chart" . }}
  annotations:
    # Instruct Argo CD to ignore immutable PVC field differences
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /spec/storageClassName
      - /spec/volumeName
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
