{{- if .Values.persistence.enabled }}
{{- $pvcName := printf "%s-media" (include "app.fullname" .) }}
{{- $existing := lookup "v1" "PersistentVolumeClaim" .Release.Namespace $pvcName }}
{{- if not $existing }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    app: {{ include "app.fullname" . }}
    chart: {{ include "app.chart" . }}
  annotations:
    # Ignore immutable fields for ArgoCD
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /spec/storageClassName
      - /spec/volumeName
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
{{- end }}
